
name: Build

permissions:
  contents: write

on:
    push:
        tags:
          - "v*.*.*"

jobs:
    release:
        name: build and release electron app
        runs-on: ${{ matrix.os }}

        strategy:
          fail-fast: false
          matrix:
            os: [windows-latest]

        steps:
          - name: Check out git repository
            uses: actions/checkout@v3.0.0

          - name: Install Node.js
            uses: actions/setup-node@v3.0.0
            with:
              node-version: "20"

          - name: Install Dependencies
            run: yarn install

          - name: Build Electron App
            run: yarn make
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: upload artifacts
            uses: actions/upload-artifact@v3.1.2
            with:
              name: ${{ matrix.os }}
              path: out/make
#          - name: zip release
#            run: Compress-Archive -Path out/thundersub-win32-x64/* -Destination windows-latest.zip
          - name: release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
              files: out/make/**
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}